/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElMessageBox: typeof import('element-plus/es')['ElMessageBox']
  const ElText: typeof import('element-plus/es')['ElText']
}
