/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EditorContainer: typeof import('./src/components/container/EditorContainer.vue')['default']
    MaterialList: typeof import('./src/components/material/MaterialList.vue')['default']
    Nav: typeof import('./src/components/nav/Nav.vue')['default']
    Operator: typeof import('./src/components/operator/Operator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
  }
}
