/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CanvasList: typeof import('./src/components/canvas/CanvasList.vue')['default']
    CanvasListItem: typeof import('./src/components/canvas/CanvasListItem.vue')['default']
    Control: typeof import('./src/components/control/Control.vue')['default']
    Dialog: typeof import('./src/components/dialog/Dialog.vue')['default']
    EditorContainer: typeof import('./src/components/container/EditorContainer.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElFormTiem: typeof import('element-plus/es')['ElFormTiem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    LibraryArea: typeof import('./src/components/LibraryArea.vue')['default']
    MaterialList: typeof import('./src/components/material/MaterialList.vue')['default']
    MaterialListItem: typeof import('./src/components/material/MaterialListItem.vue')['default']
    Nav: typeof import('./src/components/nav/Nav.vue')['default']
    NavList: typeof import('./src/components/nav/NavList.vue')['default']
    NavListItem: typeof import('./src/components/nav/NavListItem.vue')['default']
    Operator: typeof import('./src/components/operator/Operator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
  }
}
